# Generated by Django 5.1.7 on 2025-03-18 02:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0002_tempmodel_delete_customuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("naver_id", models.CharField(max_length=255, unique=True)),
                ("nickname", models.CharField(max_length=255)),
                (
                    "profile_image",
                    models.URLField(blank=True, max_length=2000, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("gender", models.CharField(blank=True, max_length=10, null=True)),
                ("age", models.CharField(blank=True, max_length=10, null=True)),
                ("birthday", models.CharField(blank=True, max_length=10, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("daily_query_limit", models.IntegerField(default=10)),
                ("daily_queries_used", models.IntegerField(default=0)),
                (
                    "last_query_reset",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_premium", models.BooleanField(default=False)),
                ("premium_until", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
