# Generated by Django 5.1.7 on 2025-03-18 02:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NaverUserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naver_id", models.CharField(max_length=255, unique=True)),
                ("nickname", models.CharField(max_length=255)),
                (
                    "profile_image",
                    models.URLField(blank=True, max_length=2000, null=True),
                ),
                ("gender", models.CharField(blank=True, max_length=10, null=True)),
                ("age", models.CharField(blank=True, max_length=10, null=True)),
                ("birthday", models.CharField(blank=True, max_length=10, null=True)),
                ("daily_query_limit", models.IntegerField(default=10)),
                ("daily_queries_used", models.IntegerField(default=0)),
                (
                    "last_query_reset",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_premium", models.BooleanField(default=False)),
                ("premium_until", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="naver_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="CustomUser",),
    ]
