# Generated by Django 5.1.7 on 2025-03-21 01:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="daily_queries_used",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="daily_query_limit",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="user",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="last_query_reset",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="user",
            name="mobile",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="premium_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
