# Generated by Django 5.1.7 on 2025-03-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_naveruserprofile_delete_customuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="naveruserprofile",
            name="birthyear",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="naveruserprofile",
            name="mobile",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="naveruserprofile",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
