# Generated by Django 5.1.7 on 2025-03-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_username_user_unique_user_email"),
    ]

    operations = [
        migrations.RemoveConstraint(model_name="user", name="unique_user_email",),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                help_text="Required. 150 characters or fewer. Used for authentication only.",
                max_length=150,
                unique=True,
            ),
        ),
    ]
