# Generated by Django 5.1.7 on 2025-03-21 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_user_unique_user_email_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                editable=False,
                help_text="Internal field used for authentication only.",
                max_length=150,
                unique=True,
            ),
        ),
    ]
