# Generated by Django 5.1.7 on 2025-04-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="naver_access_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
