# Generated by Django 5.1.7 on 2025-04-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_user_naver_access_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="information",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Structured user profile information",
                null=True,
            ),
        ),
    ]
