# Generated by Django 5.1.7 on 2025-06-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HtmlContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="콘텐츠의 제목을 입력하세요.", max_length=200),
                ),
                (
                    "zip_file",
                    models.FileField(
                        help_text="HTML 파일과 이미지 폴더가 포함된 ZIP 파일을 업로드하세요.",
                        upload_to="zips/",
                    ),
                ),
                (
                    "entry_html_path",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
