# Generated by Django 5.1.7 on 2025-06-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_uploader", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="htmlcontent",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="htmlcontent",
            name="title",
            field=models.CharField(help_text="웹페이지에 표시될 제목을 입력하세요.", max_length=200),
        ),
        migrations.AlterField(
            model_name="htmlcontent",
            name="zip_file",
            field=models.FileField(
                help_text="노션에서 HTML 형식으로 내보내기 하고, ZIP 파일 형태 그대로 업로드하세요.",
                upload_to="zips/",
            ),
        ),
    ]
