# Generated by Django 5.1.7 on 2025-06-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "content_uploader",
            "0002_htmlcontent_updated_at_alter_htmlcontent_title_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="NotionContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="웹페이지에 표시될 제목을 입력하세요.", max_length=200),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="웹페이지에 표시될 짧은 설명을 입력하세요. (비워둘 경우, 본문 앞부분 일부가 표시됩니다.)",
                    ),
                ),
                (
                    "thumbnail_img",
                    models.ImageField(
                        blank=True,
                        help_text="썸네일 이미지를 업로드하세요. (비워둘 경우, 본문 가장 첫 이미지가 썸네일이 됩니다.)",
                        null=True,
                        upload_to="",
                    ),
                ),
                (
                    "zip_file",
                    models.FileField(
                        help_text="노션에서 HTML 형식으로 내보내기 하고, ZIP 파일 형태 그대로 업로드하세요.",
                        upload_to="zips/",
                    ),
                ),
                (
                    "entry_html_path",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(name="HtmlContent",),
    ]
