# Generated by Django 5.1.7 on 2025-06-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_uploader", "0003_notioncontent_delete_htmlcontent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notioncontent",
            name="zip_file",
            field=models.FileField(
                blank=True,
                help_text="노션에서 HTML 형식으로 내보내기 하고, ZIP 파일 형태 그대로 업로드하세요.",
                null=True,
                upload_to="",
            ),
        ),
    ]
