# Generated by Django 5.1.7 on 2025-06-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_uploader", "0004_alter_notioncontent_zip_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notioncontent",
            old_name="entry_html_path",
            new_name="html_path",
        ),
        migrations.RenameField(
            model_name="notioncontent",
            old_name="thumbnail_img",
            new_name="thumbnail_img_path",
        ),
        migrations.AddField(
            model_name="notioncontent",
            name="contents_img_path",
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
