# Generated by Django 5.1.7 on 2025-03-20 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_prompt_abtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abtest',
            name='winner',
            field=models.CharField(blank=True, choices=[('a', 'Prompt A'), ('b', 'Prompt B')], max_length=10, null=True),
        ),
    ]
