# Generated by Django 5.1.7 on 2025-03-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_alter_abtest_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='abtest',
            name='chunk_overlap',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abtest',
            name='chunk_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abtest',
            name='llm_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abtest',
            name='llm_top_k',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
