# Generated by Django 5.1.7 on 2025-03-21 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_abtest_chunk_overlap_abtest_chunk_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='prompt_id',
        ),
    ]
