# Generated by Django 5.1.7 on 2025-03-27 16:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0005_remove_prompt_prompt_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="session_nonce",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.DeleteModel(name="ABTest",),
        migrations.DeleteModel(name="Prompt",),
    ]
