<<<<<<< HEAD
# Generated by Django 5.1.7 on 2025-03-28 10:28
=======
# Generated by Django 5.1.7 on 2025-03-28 06:35
>>>>>>> f7b0051ac8a718ee3370f5d946cf90b0b7017eec

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('chatbot', '0006_chatsession_session_nonce_delete_abtest_and_more'),
=======
        ("chatbot", "0006_chatsession_session_nonce_delete_abtest_and_more"),
>>>>>>> f7b0051ac8a718ee3370f5d946cf90b0b7017eec
    ]

    operations = [
        migrations.AddField(
<<<<<<< HEAD
            model_name='chatsession',
            name='request_sent',
=======
            model_name="chatsession",
            name="request_sent",
>>>>>>> f7b0051ac8a718ee3370f5d946cf90b0b7017eec
            field=models.BooleanField(default=False),
        ),
    ]
