# Generated by Django 5.1.7 on 2025-03-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0006_chatsession_session_nonce_delete_abtest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="request_sent",
            field=models.BooleanField(default=False),
        ),
    ]
