# Generated by Django 5.1.7 on 2025-04-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_chatsession_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(choices=[('user', '사용자'), ('assistant', '창플 AI')], max_length=10),
        ),
    ]
