# Generated by Django 5.1.7 on 2025-04-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_chatsession_is_updated_alter_chatmessage_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='updated_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
