# Generated by Django 5.1.7 on 2025-04-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_chatsession_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='user_liked',
            field=models.BooleanField(default=False),
        ),
    ]
