# Generated by Django 5.1.7 on 2025-04-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_chatmessage_user_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='user_disliked',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='user_liked',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
