# Generated by Django 5.1.7 on 2025-05-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0013_chatmessage_helpful_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='human_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
