# Generated by Django 5.1.7 on 2025-05-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0014_chatmessage_human_feedback"),
    ]

    operations = [
        migrations.RemoveField(model_name="chatmessage", name="user_disliked",),
        migrations.RemoveField(model_name="chatmessage", name="user_liked",),
        migrations.AddField(
            model_name="chatmessage",
            name="good_or_bad",
            field=models.CharField(
                blank=True,
                choices=[("good", "GOOD"), ("bad", "BAD")],
                default=None,
                max_length=10,
                null=True,
            ),
        ),
    ]
