# Generated by Django 5.2.10 on 2026-01-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentViewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, help_text='조회한 시간')),
            ],
            options={
                'verbose_name': '콘텐츠 조회 이력',
                'verbose_name_plural': '콘텐츠 조회 이력',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='NotionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='웹페이지에 표시될 제목을 입력하세요.', max_length=200, verbose_name='제목')),
                ('description', models.TextField(blank=True, help_text='웹페이지에 표시될 짧은 설명을 입력하세요. (2 ~ 4 문장 정도)', verbose_name='설명')),
                ('thumbnail_img_path', models.ImageField(blank=True, help_text='썸네일 이미지를 업로드하세요.', null=True, upload_to='', verbose_name='썸네일 이미지')),
                ('zip_file', models.FileField(blank=True, help_text='노션에서 HTML 형식으로 내보내기 한 뒤, 얻어지는 .zip 파일을 그대로 업로드하세요.', null=True, upload_to='', verbose_name='.zip 파일')),
                ('is_preferred', models.BooleanField(default=False, help_text='체크시 컨텐츠 목록에서 [인기칼럼] 섹션에 상위 노출됩니다.', verbose_name='인기 칼럼')),
                ('html_path', models.CharField(blank=True, editable=False, help_text='처리된 HTML 파일의 상대 경로입니다.', max_length=255)),
                ('contents_img_path', models.CharField(blank=True, editable=False, help_text='콘텐츠에 포함된 이미지들이 저장된 디렉토리의 상대 경로입니다.', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '창플 컨텐츠 관리',
                'verbose_name_plural': '창플 컨텐츠 관리',
            },
        ),
    ]
