# Generated by Django 5.2.10 on 2026-01-28 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contentviewhistory',
            name='user',
            field=models.ForeignKey(help_text='콘텐츠를 조회한 사용자', on_delete=django.db.models.deletion.CASCADE, related_name='content_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentviewhistory',
            name='content',
            field=models.ForeignKey(help_text='조회된 콘텐츠', on_delete=django.db.models.deletion.CASCADE, related_name='view_history', to='content.notioncontent'),
        ),
        migrations.AddIndex(
            model_name='contentviewhistory',
            index=models.Index(fields=['user', '-viewed_at'], name='content_con_user_id_6abf3b_idx'),
        ),
        migrations.AddIndex(
            model_name='contentviewhistory',
            index=models.Index(fields=['content', '-viewed_at'], name='content_con_content_89a199_idx'),
        ),
    ]
