"""
State definitions for LangGraph RAG agent.

Ported from changple2/chatbot/bot.py with modifications for
service-oriented architecture.
"""

from dataclasses import dataclass, field
from typing import Annotated, Literal, Optional, Union

from langchain_core.documents import Document
from langgraph.graph import MessagesState
from pydantic import BaseModel


class Router(BaseModel):
    """
    Query routing classification.

    Attributes:
        type: Either "retrieval_required" for complex queries or "just_respond" for simple ones
    """

    type: Literal["retrieval_required", "just_respond"]


@dataclass(kw_only=True)
class QueryState:
    """
    Private state for individual document retrieval operations.

    This is used in parallel retrieval to pass query information to each
    retrieve_documents node execution.
    """

    query: str


def reduce_docs(
    existing: Optional[list[Document]],
    new: Union[list[Document], str, dict],
) -> list[Document]:
    """
    Reduce and process documents based on the input type.

    This function handles various input types and converts them into a sequence of Document objects.
    It also combines existing documents with new ones based on the document ID.

    Args:
        existing: The existing docs in the state, if any
        new: The new input to process (Documents, dict, or "delete" command)

    Returns:
        Combined list of Document objects
    """
    if new == "delete":
        return []

    if isinstance(new, dict):
        return new["documents"]

    existing_list = list(existing) if existing else []
    return existing_list + new


@dataclass(kw_only=True)
class AgentState(MessagesState):
    """
    Main state object for the RAG agent graph.

    Extends MessagesState to include conversation context plus additional
    fields needed for document retrieval and routing.

    Attributes:
        router: Classification result for query routing
        documents: Retrieved and processed documents (with reduce_docs annotation)
        answer: Final answer generated by the agent
        query: Current user query being processed
        retrieve_queries: Multiple search queries generated for parallel retrieval
        helpful_documents: List of document indices deemed relevant to the query
        allowed_authors: List of authors to filter documents by
        user_attached_content: Content attached by user (from NotionContent)
        source_documents: Source document metadata for citations
    """

    router: Router = field(default_factory=lambda: Router(type="retrieval_required"))
    documents: Annotated[list[Document], reduce_docs] = field(default_factory=list)
    answer: str = field(default="")
    query: str = field(default="")
    retrieve_queries: list[str] = field(default_factory=list)
    helpful_documents: list[int] = field(default_factory=list)
    allowed_authors: list[str] = field(default_factory=list)
    user_attached_content: Optional[str] = field(default=None)
    source_documents: list[dict] = field(default_factory=list)
