"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# load .env file
load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-x(8li5z)2_#!*&4n0tv32w_ahb**l!l5gc4sv&=*u1f)pkv=#6"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "localhost").split(",")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third party apps
    "rest_framework",
    "social_django",
    # Local apps
    "users",
    "scraper",
    "chatbot",
    "notifications",
    "django_rq",
]

# Custom User Model
AUTH_USER_MODEL = "users.User"

# Authentication Backends
AUTHENTICATION_BACKENDS = [
    "users.backends.EmailBackend",  # Email auth backend
    "django.contrib.auth.backends.ModelBackend",  # Default model backend
    "users.backends.SocialAuthBackend",  # Social auth backend
    "social_core.backends.naver.NaverOAuth2",  # Naver OAuth2
]

# Social Auth Settings
SOCIAL_AUTH_NAVER_KEY = os.environ.get("SOCIAL_AUTH_NAVER_CLIENT_ID")
SOCIAL_AUTH_NAVER_SECRET = os.environ.get("SOCIAL_AUTH_NAVER_CLIENT_SECRET")
SOCIAL_AUTH_LOGIN_REDIRECT_URL = "/"
SOCIAL_AUTH_LOGIN_ERROR_URL = "/login-error/"
SOCIAL_AUTH_NEW_USER_REDIRECT_URL = "/"
SOCIAL_AUTH_NEW_ASSOCIATION_REDIRECT_URL = "/"

# If login works fine but there are state verification errors,
# you can uncomment this line to disable state verification
# SOCIAL_AUTH_DISABLE_STATE_VERIFICATION = True

# Naver specific settings
SOCIAL_AUTH_NAVER_CALLBACK_URL = os.environ.get(
    "SOCIAL_AUTH_NAVER_CALLBACK_URL",
    "http://localhost:8000/naver/callback/",  # Development default
)

# Ensure the callback URL doesn't end with a query string
if "?" in SOCIAL_AUTH_NAVER_CALLBACK_URL:
    SOCIAL_AUTH_NAVER_CALLBACK_URL = SOCIAL_AUTH_NAVER_CALLBACK_URL.split("?")[0]

# Social Auth Pipeline
SOCIAL_AUTH_PIPELINE = (
    "social_core.pipeline.social_auth.social_details",
    "social_core.pipeline.social_auth.social_uid",
    "social_core.pipeline.social_auth.auth_allowed",
    "social_core.pipeline.social_auth.social_user",
    "social_core.pipeline.user.get_username",
    "social_core.pipeline.social_auth.associate_by_email",
    "users.pipeline.create_user",
    "social_core.pipeline.social_auth.associate_user",
    "social_core.pipeline.social_auth.load_extra_data",
    "social_core.pipeline.user.user_details",
)

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "social_django.middleware.SocialAuthExceptionMiddleware",
    "users.middleware.NaverAuthMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "social_django.context_processors.backends",
                "social_django.context_processors.login_redirect",
                "config.context_processors.settings_context",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Authentication Settings
LOGIN_URL = "/"
LOGIN_REDIRECT_URL = "/"

# Logging Configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": "naver_auth.log",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "users": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": True,
        },
        "social_core": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": True,
        },
        "social_django": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": True,
        },
    },
}
# Redis configuration for RQ
REDIS_URL = os.environ.get("REDIS_URL", "redis://redis:6379/0")

# Redis and RQ Configuration
RQ_QUEUES = {
    "default": {
        "HOST": "localhost",
        "PORT": 6379,
        "DB": 0,
        "DEFAULT_TIMEOUT": 360,
    },
    "high": {
        "HOST": "localhost",
        "PORT": 6379,
        "DB": 0,
        "DEFAULT_TIMEOUT": 500,
    },
    "low": {
        "HOST": "localhost",
        "PORT": 6379,
        "DB": 0,
        "DEFAULT_TIMEOUT": 1200,
    },
}

# If using a password with Redis
# RQ_QUEUES['default']['PASSWORD'] = 'password'

# Specify the Redis client to be used
RQ_SHOW_ADMIN_LINK = True

# Pinecone settings
PINECONE_ENVIRONMENT = os.environ.get("PINECONE_ENVIRONMENT")
PINECONE_INDEX_NAME = os.environ.get("PINECONE_INDEX_NAME")

# embedding model settings
EMBEDDING_MODEL = "text-embedding-3-large"

# text splitter settings
TEXT_SPLITTER_CHUNK_SIZE = 1000
TEXT_SPLITTER_CHUNK_OVERLAP = 200

# LLM model settings
LLM_MODEL = os.getenv("LLM_MODEL", "gpt-4o")
LLM_TEMPERATURE = os.getenv("LLM_TEMPERATURE", 0.7)
LLM_STREAMING = os.getenv("LLM_STREAMING", True)
LLM_TOP_K = os.getenv("LLM_TOP_K", 5)

# Retriever Settings
NUM_DOCS = 5  # number of retrieved documents
HYBRID_ALPHA = 0.5  # weight between vector and BM25 scores (1: vector, 0: BM25)
WHOOSH_INDEX_DIR = "chatbot/data/whoosh_index"  # Whoosh index directory
KEYWORD_MODEL = "gpt-4o-mini"  # LLM for keyword extraction

# Publication data
PUBLICATION_PATH = os.environ.get(
    "PUBLICATION_PATH",
    os.path.join(BASE_DIR, "chatbot", "data", "창플 출판 서적 요약.txt"),
)

# RQ Scheduler Configuration
RQ_SCHEDULER_INTERVAL = 60  # Check for scheduled tasks every 60 seconds
RQ_SCHEDULER_QUEUES = ["default"]  # Only check the default queue
RQ_SCHEDULER_QUEUES = ["default", "high", "low"]  # Check all queues
RQ_SCHEDULER_QUEUES = ["default", "high", "low"]  # Check all queues
RQ_SCHEDULER_QUEUES = ["default", "high", "low"]  # Check all queues

# Email settings
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend"
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.your-email-provider.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 587))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "Your App <noreply@yourapp.com>")
