# Generated by Django 5.2.10 on 2026-01-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('author_group', models.CharField(choices=[('창플', '창플'), ('팀비즈니스_브랜드', '팀비즈니스 브랜드'), ('기타', '기타')], default='창플', help_text='작성자 그룹', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='체크가 안되어있을 경우, 벡터화되지 않음(해당 작성자의 게시글 사용 안됨)')),
            ],
            options={
                'verbose_name': 'Allowed Author',
                'verbose_name_plural': 'Allowed Authors',
                'ordering': ['author_group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GoodtoKnowBrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_goodto_know', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Good to Know Brand',
                'verbose_name_plural': 'Good to Know Brands',
            },
        ),
        migrations.CreateModel(
            name='BatchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_type', models.CharField(choices=[('summarize', 'Summarization'), ('embed', 'Embedding')], max_length=20)),
                ('provider', models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI')], max_length=20)),
                ('job_id', models.CharField(blank=True, help_text="Provider's job/batch ID (job_name for Gemini, batch_id for OpenAI)", max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('post_ids', models.JSONField(default=list, help_text='List of NaverCafeData post_ids in this batch')),
                ('result_file', models.CharField(blank=True, help_text='Path to results file if file-based', max_length=500)),
                ('error_message', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Batch Job',
                'verbose_name_plural': 'Batch Jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='scraper_bat_status_8d95c9_idx'), models.Index(fields=['job_type', 'status'], name='scraper_bat_job_typ_e651d6_idx')],
            },
        ),
        migrations.CreateModel(
            name='NaverCafeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=200)),
                ('published_date', models.DateTimeField(db_index=True)),
                ('post_id', models.IntegerField(unique=True)),
                ('notation', models.JSONField(blank=True, null=True)),
                ('keywords', models.JSONField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('possible_questions', models.JSONField(blank=True, help_text='원문이 대답이 될 수 있는 예상 질문 리스트', null=True)),
                ('ingested', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Naver Cafe Data',
                'verbose_name_plural': 'Naver Cafe Data',
                'indexes': [models.Index(fields=['author'], name='scraper_nav_author_965b27_idx'), models.Index(fields=['ingested'], name='scraper_nav_ingeste_95285e_idx')],
            },
        ),
        migrations.CreateModel(
            name='PostStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_id', models.IntegerField(unique=True)),
                ('status', models.CharField(choices=[('DELETED', 'Deleted'), ('ERROR', 'Error'), ('SAVED', 'Saved')], max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Post Status',
                'verbose_name_plural': 'Post Statuses',
                'indexes': [models.Index(fields=['post_id'], name='scraper_pos_post_id_7423d3_idx'), models.Index(fields=['status'], name='scraper_pos_status_119b26_idx')],
            },
        ),
    ]
