# Generated by Django 5.1.7 on 2025-03-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="allowedcategory",
            options={
                "ordering": ["category_group", "name"],
                "verbose_name": "Allowed Category",
                "verbose_name_plural": "Allowed Categories",
            },
        ),
        migrations.AddField(
            model_name="allowedcategory",
            name="category_group",
            field=models.CharField(
                choices=[
                    ("창플지기_칼럼", "창플지기 칼럼"),
                    ("창플_이야기", "창플 이야기"),
                    ("창플_아키", "창플 아키"),
                    ("창플_프랜차이즈", "창플 프랜차이즈"),
                    ("창플_팀비즈니스", "창플 팀비즈니스"),
                    ("창플_파트너스", "창플 파트너스"),
                    ("알아두면_좋은_이야기", "알아두면 좋은 이야기"),
                    ("창플_Youtube영상", "창플 Youtube영상"),
                    ("창플인터뷰", "창플인터뷰"),
                    ("창플지기_상담", "창플지기 상담"),
                    ("처음왔어요", "처음왔어요"),
                    ("창플_커뮤니티", "창플 커뮤니티"),
                    ("창플카페_이용방법", "창플카페 이용방법"),
                    ("기타", "기타"),
                ],
                default="기타",
                help_text="Category group for organization",
                max_length=50,
            ),
        ),
    ]
