# Generated by Django 5.1.7 on 2025-03-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0002_alter_allowedcategory_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_id", models.IntegerField(unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DELETED", "Deleted"),
                            ("NOT_FOUND", "Not Found"),
                            ("ACCESS_DENIED", "Access Denied"),
                            ("ERROR", "Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("last_checked", models.DateTimeField(auto_now=True)),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if any", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Post Status",
                "verbose_name_plural": "Post Statuses",
                "indexes": [
                    models.Index(
                        fields=["post_id"], name="scraper_pos_post_id_7423d3_idx"
                    )
                ],
            },
        ),
    ]
