# Generated by Django 5.1.7 on 2025-03-20 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0003_poststatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poststatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("DELETED", "Deleted"),
                    ("ERROR", "Error"),
                    ("SAVED", "Saved"),
                ],
                max_length=20,
            ),
        ),
    ]
