# Generated by Django 5.1.7 on 2025-03-20 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_alter_poststatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navercafedata',
            name='published_date',
            field=models.CharField(max_length=200),
        ),
    ]
