# Generated by Django 5.1.7 on 2025-03-20 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0005_alter_navercafedata_published_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="navercafedata",
            name="published_date",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
