# Generated by Django 5.1.7 on 2025-03-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0006_alter_navercafedata_published_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="navercafedata",
            name="vectorized",
            field=models.BooleanField(default=False),
        ),
    ]
