# Generated by Django 5.1.7 on 2025-03-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0006_alter_navercafedata_published_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllowedAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "author_group",
                    models.CharField(
                        choices=[
                            ("창플", "창플"),
                            ("팀비즈니스_브랜드_대표", "팀비즈니스 브랜드 대표"),
                            ("기타", "기타"),
                        ],
                        default="창플",
                        help_text="Author group for organization",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="If unchecked, this author's posts will not be vectorized",
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Allowed Author",
                "verbose_name_plural": "Allowed Authors",
                "ordering": ["author_group", "name"],
            },
        ),
        migrations.AddField(
            model_name="navercafedata",
            name="vectorized",
            field=models.BooleanField(default=False),
        ),
    ]
