# Generated by Django 5.1.7 on 2025-04-02 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0008_allowedauthor"),
    ]

    operations = [
        migrations.RemoveField(model_name="navercafedata", name="vectorized",),
    ]
