# Generated by Django 5.1.7 on 2025-04-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0009_remove_navercafedata_vectorized"),
    ]

    operations = [
        migrations.AddField(
            model_name="navercafedata",
            name="keywords",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="navercafedata",
            name="notation",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
