# Generated by Django 5.1.7 on 2025-04-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0010_navercafedata_keywords_navercafedata_notation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navercafedata',
            name='notation',
        ),
        migrations.AddField(
            model_name='navercafedata',
            name='summary',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
