# Generated by Django 5.1.7 on 2025-04-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0012_navercafedata_possible_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='navercafedata',
            name='notation',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
