# Generated by Django 5.1.7 on 2025-04-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0013_navercafedata_notation"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisallowedBrands",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("is_disallowed", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Disallowed Brand",
                "verbose_name_plural": "Disallowed Brands",
            },
        ),
        migrations.CreateModel(
            name="GoodtoKnowBrands",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("is_goodto_know", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Good to Know Brand",
                "verbose_name_plural": "Good to Know Brands",
            },
        ),
    ]
