# Generated by Django 5.1.7 on 2025-04-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0014_disallowedbrands_goodtoknowbrands"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodtoknowbrands",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
