# Generated by Django 5.1.7 on 2025-03-22 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="emaillog", name="template",),
        migrations.DeleteModel(name="EmailTemplate",),
    ]
